# Operadores de bits
print("\n===== Operadores de bits ====")
print("E (&)")
print("1 & 0 =", (1 & 0))
print("1 & 5 =", (1 & 5))
print("OU (|)")
print("1 | 0 = ", (1 | 0))
print("1 | 5 = ", (1 | 5))
print("OU Exclusivo (^)")
print("1 ^ 0 = ", (1 ^ 0))
print("1 ^ 5 = ", (1 ^ 5))
print("Deslocamento a esquerda (<<)")
print("1 << 5 = ", (1 << 5))
print("Deslocamento a direita (>>)")
print("1 >> 5 = ", (1 >> 5))
print("Inversão de bits (~)")
print("~4 = ", (~4))
