# operadores
print("\n===== Operadores ====")
print("Adição (+)")
print("3 + 2 = ", (3 + 2))
print("Subtração (-)")
print("3 - 2 = " ,(3 - 2))
print("Multiplicação (*)")
print("3 * 2 = ", (3 * 2))
print("Divisão (/)")
print("3 / 2 = ", (3 / 2))
print("Divisão Inteira (//)")
print("3 // 2 = ",(3 // 2))
print("Módulo (%)")
print("3 % 2 = ", (3 % 2))
print("Potenciação (**)")
print("3 ** 2 = ", (3 ** 2))
